title: Hesong Li's Homepage
page-top-title: Hesong Li (李和松)
top-section-bg-text: AI for Electron Microscopy Imaging
home-subtitle: Hesong Li | 李和松
copyright-text: '&copy; Hesong Li 2026. All Rights Reserved.'
